language: php

dist: precise

language: php


php:
 - '5.4'
  - '5.6'
  - '7.0'
  - 7.2
  
  
env:
  - DB_CONNECTION=mysql
  
cache:
    directorie:
      - node_modules
      - vendor	  
	  
before_script:
#     - sudo apt-get install php-mysql
      - cp .env.travis .env
	  - composer self-update
	  - composer install --no-interaction
	  - composer refresh-db
	  - php artisan key:generate
	  - php artisan migrate:fresh --seed --no-interaction -vvv
	  - composer test
script:
      - vendor/bin/phpunit